language: node_js
node_js: node
script: npm test && npm run coverage
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
# deploy:
#   provider: heroku
#   api_key:
#     secure: WVA22E6HfAg7tKoz36JqqoAJ3t0HvpnOm6UGljqc9fRM2QEHl65IuqG4YNtTPigjHl/QLCxCV99Zy9q8MSdzqVlaxUZHQEPej1Mn4hUBW/mhdsxmGW3LC0mI00HCYIP4cicm8aQIjr+awcq1efSihrPgGzsAOJIX57KKTdqHyjvzSeAbT1CRFEmggm4rqcRATuTaHoP2XFALurwKrEpJrYGlrmGzsYrUwXpGmhoL6nA5ocVNh1kaXcELsFdC+UaH3hY7L2EPQ0Y1QyZXBhCsTV8r0AMdBvcpBFhawy3uuNNPC455pQ8N4N+xTfH756WWY3s+IhHbg6m9+QIDWLp15d3R92IF+yFNAfnHPuCtPe0/j2+xgl8qUJlIhPEMNSDLMErcZ6/o68PsymuspuQ55IAGfPOYmdjuIpkkyQ1Ql+9LveOkVccC2JUZP7eF9PoTE8ZdH56rf1WqiBWueW6eJnyQTlag6JM0ZXvAbNMjHMBEl594+6jRlnu8waNExB98cZIft8JgucHh1Ft9kHpNNdEFLN/KrVM5RbHizhHFlSBiEppUCFnGg4DgDQpXdr6nfwYZ87aMoyVjeBHuT3CmjqIe3YPMx/oQcGkTZuF9jI/Kjq5fpCCAEIaCtLSSr5HclnkRMljzeEEd0QEABC0itKow+UlqO8+om2IjqEEp2iw=
#   app: bjohnson-time-tracker
#   on:
#     repo: benjaminj6/time-tracker
